/* 정치인 상세정보 */
SELECT POLITICIAN_ID
     , POL.PARTY_ID
     , POL.PARTY_NAME
     , POL.NAME
     , POL.ENG_NM
     , POL.ELECTORAL_DISTRICT
     , POL.PHOTO_URL
     , POL.BIRTHDAY
     , POL.REELE_GBN_NM
     , POL.MEM_TITLE
     , POL.MONA_CD 
  FROM POLITICIANS POL
 WHERE MONA_CD = ?