SELECT POLITICIAN_ID
     , POL.PARTY_ID
     , PAR.PARTY_NAME
     , POL.NAME
     , POL.ENG_NM
     , POL.ELECTORAL_DISTRICT
     , POL.PHOTO_URL
     , POL.BIRTHDAY
     , POL.REELE_GBN_NM
     , POL.MONA_CD 
  FROM POLITICIANS POL 
  JOIN PARTIES PAR
    ON PAR.PARTY_ID = POL.PARTY_ID
 ORDER BY POL.NAME